eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 8081
spring:
    application:
        name: product-user-login-service
    datasource:
        driverClassName: org.h2.Driver
        password: user
        url: jdbc:h2:mem:shoppingcartproduct
        username: user
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create
        show-sql: true
